const backgroundimage = "images/background.png";
const appicon = "images/icon.png";
const userdummyimg = "images/profileimg.png";
const dailyexcimg = "images/dailyexercise.png";
const mindfulnessexcimg = "images/mindfullnessexcercise.png";
const meditationexc = "images/meditationexc.png";
const breathing = "images/breathing.png";
const eyes = "images/eyes.png",
    journaling = "images/journaling.png",
    jump = "images/jump.png",
    mediation = "images/meditation.png",
    plank = "images/plank.png",
    relaxation = "images/relaxation.png",
    squat = "images/squat.png",
    stretch = "images/stretch.png",
    things = "images/things.png",
    listen = "images/listen.png";
const homeimg = "images/home.png",
    profileimg = "images/profile.png",
    mindimg = "images/mind.png",
    forumimg = "images/forum.png";
